### ISSUE TITLE
Datasource validation error on first launch

### ISSUE THREAD

**Issue by bradleman** [szczyglis-dev/py-gpt#41]
New install of pygpt on Debian 12 errors when I try to launch it:
         
Traceback (most recent call last):
  File "/root/pygpt-env/bin/pygpt", line 5, in <module>
    from pygpt_net.app import run
  File "/root/pygpt-env/lib/python3.11/site-packages/pygpt_net/app.py", line 12, in <module>
    from pygpt_net.launcher import Launcher
  File "/root/pygpt-env/lib/python3.11/site-packages/pygpt_net/launcher.py", line 22, in <module>
    from pygpt_net.ui.main import MainWindow
  File "/root/pygpt-env/lib/python3.11/site-packages/pygpt_net/ui/main.py", line 16, in <module>
    from pygpt_net.container import Container
  File "/root/pygpt-env/lib/python3.11/site-packages/pygpt_net/container.py", line 25, in <module>
    from pygpt_net.core.idx import Idx
  File "/root/pygpt-env/lib/python3.11/site-packages/pygpt_net/core/idx/__init__.py", line 19, in <module>
    from pygpt_net.provider.vector_stores import Storage
  File "/root/pygpt-env/lib/python3.11/site-packages/pygpt_net/provider/vector_stores/__init__.py", line 14, in <module>
    from llama_index.core.indices.base import BaseIndex
  File "/root/pygpt-env/lib/python3.11/site-packages/llama_index/core/__init__.py", line 19, in <module>
    from llama_index.core.indices import (
  File "/root/pygpt-env/lib/python3.11/site-packages/llama_index/core/indices/__init__.py", line 4, in <module>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "/root/pygpt-env/lib/python3.11/site-packages/llama_index/core/indices/composability/__init__.py", line 4, in <module>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "/root/pygpt-env/lib/python3.11/site-packages/llama_index/core/indices/composability/graph.py", line 7, in <module>
    from llama_index.core.indices.base import BaseIndex
  File "/root/pygpt-env/lib/python3.11/site-packages/llama_index/core/indices/base.py", line 12, in <module>
    from llama_index.core.ingestion import run_transformations
  File "/root/pygpt-env/lib/python3.11/site-packages/llama_index/core/ingestion/__init__.py", line 2, in <module>
    from llama_index.core.ingestion.pipeline import (
  File "/root/pygpt-env/lib/python3.11/site-packages/llama_index/core/ingestion/pipeline.py", line 31, in <module>
    from llama_index.core.ingestion.api_utils import get_client
  File "/root/pygpt-env/lib/python3.11/site-packages/llama_index/core/ingestion/api_utils.py", line 20, in <module>
    from llama_index.core.ingestion.data_sources import (
  File "/root/pygpt-env/lib/python3.11/site-packages/llama_index/core/ingestion/data_sources.py", line 436, in <module>
    ConfigurableDataSources = build_configurable_data_source_enum()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/pygpt-env/lib/python3.11/site-packages/llama_index/core/ingestion/data_sources.py", line 350, in build_configurable_data_source_enum
    DataSource(
  File "/root/pygpt-env/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for DataSource
component_type
  subclass of BaseComponent expected (type=type_error.subclass; expected_class=BaseComponent)

Tried a couple of different venv's

**Comment by mikeybob** [comment]
Same here, except using Fedora 39. Happens if I build it from the repository or do a pip install.

**Comment by szczyglis-dev** [comment]
Fixed in [2.1.40-post1](https://github.com/szczyglis-dev/py-gpt/releases/tag/v2.1.40-post1)
