### ISSUE TITLE
cannot import name 'FileSystemReaderMixin'

### ISSUE THREAD

**Issue by sk9la** [szczyglis-dev/py-gpt#62]
Hi,

After install pygpt from pypi using pipx
`pipx install pygpt-net` I had this error
```
Traceback (most recent call last):
  File "/usr/local/bin/pygpt", line 5, in <module>
    from pygpt_net.app import run
  File "/usr/local/lib/python3/venv/pygpt-net/lib/python3.11/site-packages/pygpt_net/app.py", line 73, in <module>
    from pygpt_net.provider.loaders.web_microsoft_onedrive import Loader as MicrosoftOneDriveLoader
  File "/usr/local/lib/python3/venv/pygpt-net/lib/python3.11/site-packages/pygpt_net/provider/loaders/web_microsoft_onedrive.py", line 16, in <module>
    from llama_index.readers.microsoft_onedrive.base import OneDriveReader
  File "/usr/local/lib/python3/venv/pygpt-net/lib/python3.11/site-packages/llama_index/readers/microsoft_onedrive/__init__.py", line 1, in <module>
    from llama_index.readers.microsoft_onedrive.base import OneDriveReader
  File "/usr/local/lib/python3/venv/pygpt-net/lib/python3.11/site-packages/llama_index/readers/microsoft_onedrive/base.py", line 15, in <module>
    from llama_index.core.readers import FileSystemReaderMixin
ImportError: cannot import name 'FileSystemReaderMixin' from 'llama_index.core.readers' (/usr/local/lib/python3/venv/pygpt-net/lib/python3.11/site-packages/llama_index/core/readers/__init__.py)
```
I'm using pipx with python3.11.9

Any ideas ?

**Comment by astrojerms** [comment]
Seems to be related to this issue from llama:
https://github.com/run-llama/llama_index/issues/11336

I was able to resolve it by upgrading two llama libraries:
pip install -U llama-index-vector-stores-chroma
pip install -U llama-index-readers-file
